# vim: set ft=toml :


[project]
name = 'sudoku-solver'


[tool.pixi.workspace]
channels = ['conda-forge']
platforms = [
  'linux-64',
  'linux-aarch64',
  'osx-arm64',
]

[tool.pixi.dependencies]
python = { version = '>=3.14,<3.15' }

[tool.pixi.pypi-dependencies]
ortools = { version = '*' }

[tool.pixi.environments]
default = { solve-group = 'default' }
lint = { features = ['lint'], solve-group = 'default' }

[tool.pixi.feature.lint.pypi-dependencies]
ruff = { version = '*' }


[tool.ruff]
line-length = 100
target-version = 'py314'

[tool.ruff.format]
preview = true

[tool.ruff.lint]
future-annotations = true
# https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
ignore = [
  'ANN',  # https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
  'COM812',  # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
  'COM819',  # https://docs.astral.sh/ruff/rules/prohibited-trailing-comma/
  'CPY',  # https://docs.astral.sh/ruff/rules/#flake8-copyright-cpy
  'D1',  # https://docs.astral.sh/ruff/rules/#pydocstyle-d
  'D300',  # https://docs.astral.sh/ruff/rules/triple-single-quotes/
  'E111',  # https://docs.astral.sh/ruff/rules/indentation-with-invalid-multiple/
  'E114',  # https://docs.astral.sh/ruff/rules/indentation-with-invalid-multiple-comment/
  'E117',  # https://docs.astral.sh/ruff/rules/over-indented/
  'E741',  # https://docs.astral.sh/ruff/rules/ambiguous-variable-name/
  'ERA',  # https://docs.astral.sh/ruff/rules/#eradicate-era
  'FIX002',  # https://docs.astral.sh/ruff/rules/line-contains-todo/
  'ISC001',  # https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/
  'Q000',  # https://docs.astral.sh/ruff/rules/bad-quotes-inline-string/
  'Q001',  # https://docs.astral.sh/ruff/rules/bad-quotes-multiline-string/
  'Q002',  # https://docs.astral.sh/ruff/rules/bad-quotes-docstring/
  'Q003',  # https://docs.astral.sh/ruff/rules/avoidable-escaped-quote/
  'Q004',  # https://docs.astral.sh/ruff/rules/unnecessary-escaped-quote/
  'S603',  # https://docs.astral.sh/ruff/rules/subprocess-without-shell-equals-true/
  'S606',  # https://docs.astral.sh/ruff/rules/start-process-with-no-shell/
  'S607',  # https://docs.astral.sh/ruff/rules/start-process-with-partial-path/
  'T201',  # https://docs.astral.sh/ruff/rules/print/
  'TD002',  # https://docs.astral.sh/ruff/rules/missing-todo-author/
  'TD003',  # https://docs.astral.sh/ruff/rules/missing-todo-link/
  'W191',  # https://docs.astral.sh/ruff/rules/tab-indentation/
]
select = ['ALL']

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = []
known-local-folder = []
known-third-party = [
  'ortools',
]

[tool.ruff.lint.pydocstyle]
convention = 'pep257'
